// Decompiled with JetBrains decompiler
// Type: Imi.SteelCircus.Controls.DigitalInput
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 841B04D4-2E17-4B98-AC76-29D6D8A2480C
// Assembly location: D:\SteamLibrary\steamapps\common\Steel_Circus\sc_Data\Managed\Assembly-CSharp.dll

namespace Imi.SteelCircus.Controls
{
  public enum DigitalInput
  {
    None,
    Sprint,
    Tackle,
    PrimarySkill,
    SecondarySkill,
    ThrowBall,
    Ping,
    Emote0,
    Emote1,
    Emote2,
    Emote3,
    Spraytag0,
    Spraytag1,
    Spraytag2,
    Spraytag3,
    QuickMessage0,
    QuickMessage1,
    QuickMessage2,
    QuickMessage3,
    EmoteModifier,
    SpraytagModifier,
    QuickMessageModifier,
    MoveToBall,
    Menu,
    MouseMove,
    UICancel,
    UIMatchMakingLeave,
    UIShortcut,
    UISubmit,
    UIModifier,
    UIMenu,
    UIPrevious,
    UINext,
    UIRightTrigger,
    UILeftTrigger,
    VoiceMute,
    VoicePushToTalk,
    UIVoicePushToTalk,
    UIVoiceMute,
    UIUp,
    UIDown,
    UILeft,
    UIRight,
    UIHorizontal,
    UIVertical,
    MouseVertical,
    MouseHorizontal,
    FreeroamCButton,
    FreeroamXButotn,
    FreeroamTButton,
    FreeroamSButton,
    FreeroamDPadLeft,
    FreeroamDPadRight,
    FreeroamDPadUp,
    FreeroamDPadDown,
    FreeroamLeftTrigger1,
    FreeroamLeftTrigger2,
    FreeroamRightTrigger1,
    FreeroamRightTrigger2,
    FreeroamRightJoystickButton,
    Surrender,
  }
}
