namespace Imi.ScEvents
{
	public enum Statistics
	{
		Pass = 0,
		DoublePass = 1,
		TackleMiss = 2,
		TackleSuccess = 3,
		WasTackled = 4,
		WasStunned = 5,
		DodgeMiss = 6,
		DodgeSuccess = 7,
		GoalsScored = 8,
		OwnGoalsScored = 9,
		DamageDealt = 10,
		DamageReceived = 11,
		Kills = 12,
		Deaths = 13,
		KillAssist = 14,
		SingleStun = 15,
		DoubleStun = 16,
		TripleStun = 17,
		DoubleKill = 18,
		TripleKill = 19,
		GoalAssist = 20,
		GoalsShot = 21,
		GoalsTouchdown = 22,
		FirstGoal = 23,
		GoalsGeometry = 24,
		LongestDistanceGoal = 25,
		FirstKill = 26,
		GoalsDuringPowerplay = 27,
		PassIntercept = 28,
		PickupsCollected = 29,
		BallPossessionTime = 30,
	}
}
